### PR TITLE
feat: search returns results only within the selected folder (resolves #128)

### LINKED ISSUE #128: Search in folder isn't possible
## Describe the bug

If you select a folder and try to search something the app selects all Snippets and the search query will be performed on all snippets.

## To Reproduce

- Select a folder
- Press Ctrl+F
- Enter Search query
- app jumps to all snippets & results are a query result of all snippets

## Expected behavior

There should be just the subset of the folder in the result.

## Environment

Version: 1.3.0
OS version and name: Windows 10 Pro (Build 18363)

### PR DESCRIPTION
**Pull request by patinthehat**
This PR changes the search behavior to search snippets only within the selected folder, instead of searching all snippets.  The functionality for searching all snippets now requires the 'allSnippets' folder to be selected.
Searches can be limited to favorites, all snippets, trash, or any user defined folder.

This feature improves user experience by making it easier to limit search results, while retaining the ability to search all snippets.  It's necessary to be able to limit the number of search results, especially for users with large numbers of snippets.  This feature also helps meet the expectation that the selected folder is the folder being searched.

This closes #128.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by patinthehat** [comment]
ping @antonreshetov

**Comment by antonreshetov** [comment]
@patinthehat First of all thank you for the work you have done, but at the same time I would like to point out that before you implement something, you still need to wait for approval on it, because it may go against the vision of what the application should be. Otherwise your work may be in vain. 

P.S. when you create a PR it says so.

**Comment by patinthehat** [comment]
@antonreshetov No problem - if it's not in line with your vision for the app, please feel free to close the PR.  Thanks for the consideration! :+1:

**Comment by antonreshetov** [comment]
@patinthehat I've thought about this feature, but I'd like to see it as it works in SnippetsLab - through adding a filter to the search.

**Review by Kairavyadav — APPROVED** [review]
- []()

**Pull request closed without merging**
